/* imaginemodels.js — GENERATED by fetch-models.mjs. Do not hand-edit.
 *
 * The ImagineArt API's model list as published at
 * https://platform.imagine.art/api/models
 * on 2026-09-11 — 53 models
 * (6 image, 47 video).
 *
 * This is the floor. A signed-in account's own tool schemas are preferred
 * wherever they can be read, because they are what that account may actually
 * call; this is what is shown before anyone signs in, and what the API-key
 * transport has instead. Re-run the script when the list moves.
 *
 * These are NOT all the models imagine.art has. The product is an
 * aggregator and its own pages currently advertise
 * Seedance 2.5, Runway Gen-4.5, Kling 3.0, Google Veo 3.1, Gemini Omni Flash, WAN 3.0, FLUX 3, Hailuo 3.0 & H3 Max — none of which appear in
 * the v2 API list below. The account's own tools are the only authority;
 * this is the floor beneath them, and the products list is here so the app can say
 * out loud that the API list is behind the product rather than implying it
 * is everything.
 */
(function (SB) {
  'use strict';

  SB.ImagineModels = {
    fetchedAt: "2026-09-11",
    source: "https://platform.imagine.art/api/models",
    /* names the product advertises, for saying so — not sendable slugs */
    products: ["Seedance 2.5","Runway Gen-4.5","Kling 3.0","Google Veo 3.1","Gemini Omni Flash","WAN 3.0","FLUX 3","Hailuo 3.0 & H3 Max"],
    list: [
    { slug: "anime", kind: "image" },
    { slug: "cogvideox-5b-image-to-video", kind: "video", mode: "i2v" },
    { slug: "cogvideox-5b-text-to-video", kind: "video", mode: "t2v" },
    { slug: "fast-svd-lcm-image-to-video", kind: "video", mode: "i2v" },
    { slug: "fast-svd-lcm-text-to-video", kind: "video", mode: "t2v" },
    { slug: "fast-svd-text-to-video", kind: "video", mode: "t2v" },
    { slug: "flux-dev", kind: "image" },
    { slug: "flux-schnell", kind: "image" },
    { slug: "framepack-image-to-video", kind: "video", mode: "i2v" },
    { slug: "imagine-turbo", kind: "image" },
    { slug: "kling-v1-image-to-video", kind: "video", mode: "i2v" },
    { slug: "kling-v1-pro-image-to-video", kind: "video", mode: "i2v" },
    { slug: "kling-v1-pro-text-to-video", kind: "video", mode: "t2v" },
    { slug: "kling-v1-text-to-video", kind: "video", mode: "t2v" },
    { slug: "kling-v1.5-pro-image-to-video", kind: "video", mode: "i2v" },
    { slug: "kling-v1.5-pro-text-to-video", kind: "video", mode: "t2v" },
    { slug: "kling-v1.6-pro-image-to-video", kind: "video", mode: "i2v" },
    { slug: "kling-v1.6-pro-text-to-video", kind: "video", mode: "t2v" },
    { slug: "kling-v1.6-standard-image-to-video", kind: "video", mode: "i2v" },
    { slug: "kling-v1.6-standard-text-to-video", kind: "video", mode: "t2v" },
    { slug: "ltx-video-v095-image-to-video", kind: "video", mode: "i2v" },
    { slug: "ltx-video-v095-text-to-video", kind: "video", mode: "t2v" },
    { slug: "luma-dream-machine-image-to-video", kind: "video", mode: "i2v" },
    { slug: "luma-dream-machine-ray-2-flash-image-to-video", kind: "video", mode: "i2v" },
    { slug: "luma-dream-machine-ray-2-flash-text-to-video", kind: "video", mode: "t2v" },
    { slug: "luma-dream-machine-ray-2-image-to-video", kind: "video", mode: "i2v" },
    { slug: "luma-dream-machine-ray-2-text-to-video", kind: "video", mode: "t2v" },
    { slug: "luma-dream-machine-text-to-video", kind: "video", mode: "t2v" },
    { slug: "magi-distilled-image-to-video", kind: "video", mode: "i2v" },
    { slug: "magi-distilled-text-to-video", kind: "video", mode: "t2v" },
    { slug: "magi-image-to-video", kind: "video", mode: "i2v" },
    { slug: "magi-text-to-video", kind: "video", mode: "t2v" },
    { slug: "minimax-video-01-director-image-to-video", kind: "video", mode: "i2v" },
    { slug: "minimax-video-01-director-text-to-video", kind: "video", mode: "t2v" },
    { slug: "minimax-video-01-image-to-video", kind: "video", mode: "i2v" },
    { slug: "minimax-video-01-live-image-to-video", kind: "video", mode: "i2v" },
    { slug: "minimax-video-01-live-text-to-video", kind: "video", mode: "t2v" },
    { slug: "minimax-video-01-subject-reference-image-to-video", kind: "video", mode: "i2v" },
    { slug: "minimax-video-01-text-to-video", kind: "video", mode: "t2v" },
    { slug: "mochi-v1-text-to-video", kind: "video", mode: "t2v" },
    { slug: "pika-v2.1-text-to-video", kind: "video", mode: "t2v" },
    { slug: "pika-v2.2-text-to-video", kind: "video", mode: "t2v" },
    { slug: "pixverse-v3.5-image-to-video", kind: "video", mode: "i2v" },
    { slug: "pixverse-v3.5-text-to-video", kind: "video", mode: "t2v" },
    { slug: "pixverse-v4-image-to-video", kind: "video", mode: "i2v" },
    { slug: "pixverse-v4-text-to-video", kind: "video", mode: "t2v" },
    { slug: "realistic", kind: "image" },
    { slug: "sdxl-1.0", kind: "image" },
    { slug: "skyreels-i2v-image-to-video", kind: "video", mode: "i2v" },
    { slug: "stable-video-image-to-video", kind: "video", mode: "i2v" },
    { slug: "veo2-image-to-video", kind: "video", mode: "i2v" },
    { slug: "veo2-text-to-video", kind: "video", mode: "t2v" },
    { slug: "vidu-image-to-video", kind: "video", mode: "i2v" }
    ]
  };

})(window.SB);
