/* imagine.js — pushing a finished prompt at ImagineArt.
 *
 * Everything the prompt table needs to actually make the picture is already
 * sitting in the row: the prompt, the model it was written for, and the
 * full-size render the shot already has. Up to now the last step was manual —
 * copy the prompt, open a browser tab, find the frame, drop it in. This
 * closes that loop: one button, one generation.
 *
 * ---- the two doors ----
 *
 * ImagineArt (the company is Vyro AI) can be reached two ways, and they bill
 * differently, so both are here and the user picks:
 *
 *   oauth — sign in with the imagine.art account. A textbook OAuth 2.1 public
 *           client: open dynamic registration, PKCE S256, refresh tokens, no
 *           client secret. The token's audience is ImagineArt's hosted MCP
 *           server, so the work is done by calling MCP tools. Nothing to store
 *           or rotate, and it spends the credits the account already has.
 *
 *   key   — an API key from platform.imagine.art against the documented REST
 *           endpoints (api.vyro.ai/v2). Billed separately, but it is the
 *           surface whose image-upload contract is written down.
 *
 * There is one thing the public documentation does not say: whether an OAuth
 * access token is also accepted by the REST endpoints. If it is, the REST path
 * is strictly better for us — it takes a file upload, which is exactly what
 * image-to-video needs. So a signed-in session TRIES rest first, once, and
 * remembers the answer; if it is refused it never asks again and goes through
 * MCP tools for the rest of the session. The caller never sees which happened.
 *
 * ---- why the tool binding is defensive ----
 *
 * The REST contract is fixed and coded literally. The MCP tool list is not
 * published anywhere, and it changes as ImagineArt ships tools, so this asks
 * the server (tools/list), picks the tool whose name and description read like
 * the job, and fills its arguments by matching its own JSON schema against the
 * handful of things we have (prompt, model, aspect, a start frame). What it
 * chose is shown in Settings, because a guess the user cannot see is a guess
 * nobody can fix.
 *
 * ---- what is stored where ----
 *
 * Tokens and the API key live in localStorage, exactly like the Gemini key,
 * and never touch the .storyboard — a board stays safe to hand to someone. The
 * per-model slug and the aspect ratio DO belong to the project, because they
 * are part of how that board is made.
 */
(function (SB) {
  'use strict';

  /* ---------------- constants ---------------- */

  const RESOURCE = 'https://mcp.imagine.art/';
  const RESOURCE_META = 'https://mcp.imagine.art/.well-known/oauth-protected-resource';
  const REST = 'https://api.vyro.ai/v2';
  const MCP_PROTOCOL = '2025-06-18';
  const SCOPE = 'openid email mcp:tools';
  const CLIENT_NAME = 'Storyboarder';

  /* Read off the wire on 2026-09-11. Only used when discovery itself fails —
   * the metadata documents are the truth, and are fetched first every time. */
  const AS_FALLBACK = {
    issuer: 'https://auth.vyro.ai/apis/v1/mcp',
    authorization_endpoint: 'https://imagine.art/mcp/authorize',
    token_endpoint: 'https://auth.vyro.ai/apis/v1/mcp/token',
    registration_endpoint: 'https://auth.vyro.ai/apis/v1/mcp/register',
    userinfo_endpoint: 'https://auth.vyro.ai/apis/v1/mcp/userinfo',
    code_challenge_methods_supported: ['S256']
  };

  const K_TOK = 'sb.imagine.tokens';
  const K_CLIENT = 'sb.imagine.clients';
  const K_KEY = 'sb.imagine.apiKey';
  const K_MODE = 'sb.imagine.transport';
  const K_REST = 'sb.imagine.oauthRest';   // '' unknown | 'yes' | 'no'
  const K_CAT = 'sb.imagine.catalog';      // what the account offers, per account
  const K_DOOR = 'sb.imagine.lastDoor';    // 'mcp' | 'rest' — which one last worked
  const K_WORKED = 'sb.imagine.worked';    // slugs that have actually produced something
  const K_ORG = 'sb.imagine.org';          // every generation is billed to one

  /* ---------------- the model catalog ----------------
   *
   * Three sources, in this order:
   *
   *   the account   what a signed-in session's own MCP tools advertise in
   *                 their schemas. Authoritative: it is precisely the set
   *                 that account may call.
   *   the shipped   js/imaginemodels.js, generated by fetch-models.mjs from
   *                 ImagineArt's published listing. The floor — what anyone
   *                 sees before signing in, and all the API-key transport
   *                 has, because platform.imagine.art sends no CORS headers
   *                 and a browser cannot read that page at runtime.
   *   the last few  a hardcoded handful, for the case where neither of the
   *                 above is there at all.
   *
   * It used to be only the third, eleven slugs typed off the documentation,
   * which is why the field offered four video models when the API publishes
   * forty-seven. */
  const FALLBACK = [
    { slug: 'imagine-turbo', kind: 'image' },
    { slug: 'flux-dev', kind: 'image' },
    { slug: 'flux-schnell', kind: 'image' },
    { slug: 'sdxl-1.0', kind: 'image' },
    { slug: 'kling-v1.6-standard-image-to-video', kind: 'video', mode: 'i2v' },
    { slug: 'kling-v1.6-standard-text-to-video', kind: 'video', mode: 't2v' },
    { slug: 'minimax-video-01-director-image-to-video', kind: 'video', mode: 'i2v' }
  ];

  function shipped() {
    const m = SB.ImagineModels;
    return (m && m.list && m.list.length) ? m.list : FALLBACK;
  }

  /* "kling-v1.6-standard-image-to-video" -> "Kling v1.6 Standard · image→video".
   * Derived rather than fetched: the listing page does not publish a label in
   * anything a script can rely on, and the slug carries the whole story. */
  function labelFor(slug, mode) {
    const base = String(slug || '')
      .replace(/-(text|image)-to-video$/, '')
      .split('-')
      .map(function (w) {
        if (/^v?\d/.test(w)) return w;
        return w.charAt(0).toUpperCase() + w.slice(1);
      })
      .join(' ');
    const tail = mode === 'i2v' ? ' · image→video' : (mode === 't2v' ? ' · text→video' : '');
    return base + tail;
  }

  /* Board model names are display names; a few map onto a slug with no
   * ambiguity worth worrying about. Everything else starts blank, which reads
   * honestly in Settings as "not pointed at anything yet". */
  const GUESS = {
    'Kling': 'kling-v1.6-pro-image-to-video',
    'MiniMax H3 (Hailuo)': 'minimax-video-01-director-image-to-video',
    'LTX (LTXV 2.3)': 'ltx-video-v095-image-to-video',
    'Veo': 'veo2-image-to-video',
    'FLUX': 'flux-dev'
  };

  /* ---------------- small helpers ---------------- */

  function lsGet(k) {
    try { return JSON.parse(localStorage.getItem(k)); } catch (e) { return null; }
  }
  function lsSet(k, v) {
    try {
      if (v === null || v === undefined || v === '') localStorage.removeItem(k);
      else localStorage.setItem(k, JSON.stringify(v));
    } catch (e) { }
  }
  function lsStr(k) { try { return localStorage.getItem(k) || ''; } catch (e) { return ''; } }
  function lsPut(k, v) {
    try { v ? localStorage.setItem(k, v) : localStorage.removeItem(k); } catch (e) { }
  }

  function b64url(bytes) {
    let s = '';
    for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
    return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  }

  function randomString(n) {
    const a = new Uint8Array(n);
    crypto.getRandomValues(a);
    return b64url(a);
  }

  function sha256(text) {
    return crypto.subtle.digest('SHA-256', new TextEncoder().encode(text))
      .then(function (buf) { return b64url(new Uint8Array(buf)); });
  }

  function form(obj) {
    const b = new URLSearchParams();
    Object.keys(obj).forEach(function (k) {
      if (obj[k] !== undefined && obj[k] !== null && obj[k] !== '') b.set(k, obj[k]);
    });
    return b;
  }

  function jsonOrText(res) {
    return res.text().then(function (t) {
      let body = null;
      try { body = JSON.parse(t); } catch (e) { body = null; }
      return { body: body, text: t };
    });
  }

  /* One shape for everything that comes back wrong, so the UI never has to
   * know which door it went through. ImagineArt's REST errors are
   * {status, code, error, message}; MCP's are JSON-RPC {code, message}. */
  function apiError(res, parsed) {
    const b = parsed && parsed.body;
    const msg = (b && (b.message || b.error)) ||
      (parsed && parsed.text && parsed.text.slice(0, 200)) ||
      ('HTTP ' + (res ? res.status : '?'));
    const e = new Error(String(msg));
    e.status = res ? res.status : 0;
    e.code = b && b.code;
    e.auth = e.status === 401 || e.status === 403 || e.code === 1000 ||
      e.code === 1001 || e.code === 1002;
    return e;
  }

  function blobToDataUrl(blob) {
    return new Promise(function (res, rej) {
      const r = new FileReader();
      r.onload = function () { res(String(r.result)); };
      r.onerror = function () { rej(new Error('could not read the generated file')); };
      r.readAsDataURL(blob);
    });
  }

  function dataUrlToBlob(url) {
    return fetch(url).then(function (r) { return r.blob(); });
  }

  function wait(ms) {
    return new Promise(function (r) { setTimeout(r, ms); });
  }

  /* ---------------- where the app is served from ----------------
   *
   * The redirect target is the app's own URL with the query and hash taken
   * off. Under file:// the origin is "null", which cannot be a redirect
   * target and cannot be registered — so sign-in is refused there with a
   * reason, and the API-key door stays open. The README already asks people to
   * serve the folder over http for IndexedDB; this is the same fix.
   */
  function redirectUri() {
    if (location.protocol === 'file:') return '';
    return location.origin + location.pathname;
  }

  function signInBlocked() {
    if (!redirectUri()) {
      return 'Signing in needs the app served over http — on file:// there is no address to ' +
        'come back to. Serve the folder (any static server) or use an API key below.';
    }
    if (!(window.crypto && crypto.subtle && crypto.getRandomValues)) {
      return 'This browser does not expose WebCrypto, which the sign-in needs for PKCE.';
    }
    return '';
  }

  /* ---------------- the callback ----------------
   *
   * The redirect comes back to this same page, so there is no second file to
   * ship — which matters for an app whose whole point is that it is one file.
   * A window that loads with a code AND has an opener is the popup: it hands
   * the code back and closes. The board itself never unloads, so the file
   * handle and everything unsaved survive the sign-in.
   */
  (function catchCallback() {
    if (!window.opener || window.opener === window) return;
    const q = new URLSearchParams(location.search);
    if (!q.get('code') && !q.get('error')) return;
    try {
      window.opener.postMessage({
        sb: 'imagine-oauth',
        code: q.get('code') || '',
        state: q.get('state') || '',
        error: q.get('error') || '',
        errorDescription: q.get('error_description') || ''
      }, location.origin);
    } catch (e) { }
    /* Leave something readable behind if the close is blocked. */
    try { document.documentElement.innerHTML = '<body style="font:14px system-ui;padding:24px">Signed in — you can close this window.</body>'; } catch (e) { }
    window.close();
  })();

  /* ---------------- discovery + registration ---------------- */

  let asMeta = null;

  function discover() {
    if (asMeta) return Promise.resolve(asMeta);
    return fetch(RESOURCE_META, { headers: { Accept: 'application/json' } })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (prm) {
        const as = (prm && prm.authorization_servers && prm.authorization_servers[0]) ||
          AS_FALLBACK.issuer;
        /* RFC 8414 puts the document under the issuer's host with the path
         * appended; the resource mirrors it too, and that copy is the one that
         * is certain to be reachable. */
        return fetch(RESOURCE + '.well-known/oauth-authorization-server',
          { headers: { Accept: 'application/json' } })
          .then(function (r) { return r.ok ? r.json() : null; })
          .catch(function () { return null; })
          .then(function (meta) {
            if (meta && meta.token_endpoint) return meta;
            return fetch(as.replace(/\/+$/, '') + '/.well-known/oauth-authorization-server',
              { headers: { Accept: 'application/json' } })
              .then(function (r) { return r.ok ? r.json() : null; })
              .catch(function () { return null; });
          });
      })
      .catch(function () { return null; })
      .then(function (meta) {
        asMeta = (meta && meta.token_endpoint) ? meta : AS_FALLBACK;
        return asMeta;
      });
  }

  /* One registered client per redirect URI per browser. Registration is open —
   * no portal, no approval — but it is still a write, so the id is kept and
   * reused rather than making a new client on every sign-in. */
  function clientId(meta) {
    const uri = redirectUri();
    const all = lsGet(K_CLIENT) || {};
    if (all[uri]) return Promise.resolve(all[uri]);
    const ep = meta.registration_endpoint || AS_FALLBACK.registration_endpoint;
    return fetch(ep, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        client_name: CLIENT_NAME,
        redirect_uris: [uri],
        grant_types: ['authorization_code', 'refresh_token'],
        response_types: ['code'],
        token_endpoint_auth_method: 'none',
        scope: SCOPE,
        application_type: 'web'
      })
    }).then(function (res) {
      return jsonOrText(res).then(function (p) {
        if (!res.ok || !p.body || !p.body.client_id) throw apiError(res, p);
        all[uri] = p.body.client_id;
        lsSet(K_CLIENT, all);
        return p.body.client_id;
      });
    });
  }

  /* ---------------- tokens ---------------- */

  function tokens() { return lsGet(K_TOK) || null; }
  function setTokens(t) { lsSet(K_TOK, t || ''); notify(); }

  function isSignedIn() {
    const t = tokens();
    return !!(t && t.access_token);
  }

  function signOut() {
    setTokens(null);
    lsPut(K_REST, '');
    mcp.session = null;
    mcp.ready = null;
    mcp.tools = null;
    acct = null;
    notify();
  }

  function exchange(body) {
    return discover().then(function (meta) {
      return fetch(meta.token_endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: form(body)
      }).then(function (res) {
        return jsonOrText(res).then(function (p) {
          if (!res.ok || !p.body || !p.body.access_token) throw apiError(res, p);
          const prev = tokens() || {};
          const t = {
            access_token: p.body.access_token,
            /* A refresh response that rotates the token replaces it; one that
             * does not must not blank the one we hold. */
            refresh_token: p.body.refresh_token || prev.refresh_token || '',
            expires_at: Date.now() + (((p.body.expires_in | 0) || 3600) * 1000),
            email: prev.email || ''
          };
          setTokens(t);
          return t;
        });
      });
    });
  }

  let refreshing = null;

  /* A live access token, refreshed 60s before it lapses. Rejects — it never
   * opens a popup on its own — so the caller can say "sign in again" instead
   * of a window appearing out of nowhere mid-generation. */
  function accessToken() {
    const t = tokens();
    if (!t || !t.access_token) return Promise.reject(new Error('Not signed in to ImagineArt.'));
    if (Date.now() < (t.expires_at || 0) - 60000) return Promise.resolve(t.access_token);
    if (!t.refresh_token) return Promise.reject(sessionOver());
    if (refreshing) return refreshing;
    refreshing = discover().then(function (meta) {
      return clientId(meta);
    }).then(function (cid) {
      return exchange({
        grant_type: 'refresh_token',
        refresh_token: t.refresh_token,
        client_id: cid,
        resource: RESOURCE,
        scope: SCOPE
      });
    }).then(function (fresh) {
      refreshing = null;
      return fresh.access_token;
    }).catch(function (e) {
      refreshing = null;
      setTokens(null);
      throw sessionOver(e);
    });
    return refreshing;
  }

  function sessionOver(e) {
    const err = new Error('The ImagineArt session has expired — sign in again in Settings → ImagineArt.');
    err.auth = true;
    err.cause = e;
    return err;
  }

  /* ---------------- sign in ---------------- */

  let signingIn = null;

  function signIn() {
    const why = signInBlocked();
    if (why) return Promise.reject(new Error(why));
    if (signingIn) return signingIn;

    const uri = redirectUri();
    const state = randomString(16);
    const verifier = randomString(48);

    /* The popup is opened synchronously, inside the click, or the browser
     * blocks it — the URL is filled in once discovery answers. */
    const win = window.open('', 'imagine-signin',
      'width=520,height=760,menubar=no,toolbar=no');
    if (!win) return Promise.reject(new Error('The sign-in window was blocked — allow popups for this page and try again.'));

    signingIn = Promise.all([discover(), sha256(verifier)]).then(function (both) {
      const meta = both[0], challenge = both[1];
      return clientId(meta).then(function (cid) {
        const url = meta.authorization_endpoint + '?' + form({
          response_type: 'code',
          client_id: cid,
          redirect_uri: uri,
          scope: SCOPE,
          state: state,
          code_challenge: challenge,
          code_challenge_method: 'S256',
          /* RFC 8707 — says out loud which resource the token is for. */
          resource: RESOURCE
        }).toString();
        win.location = url;
        return awaitCode(win, state).then(function (code) {
          return exchange({
            grant_type: 'authorization_code',
            code: code,
            redirect_uri: uri,
            client_id: cid,
            code_verifier: verifier,
            resource: RESOURCE
          });
        });
      });
    }).then(function (t) {
      signingIn = null;
      return whoAmI().catch(function () { return null; })
        .then(function () { return refreshCatalog().catch(function () { return null; }); })
        .then(function () { return t; });
    }).catch(function (e) {
      signingIn = null;
      try { win.close(); } catch (x) { }
      throw e;
    });

    return signingIn;
  }

  /* Wait for the popup to hand back a code. Three ways this ends: the message
   * arrives, the user closes the window, or nothing happens for five minutes. */
  function awaitCode(win, state) {
    return new Promise(function (resolve, reject) {
      let done = false;
      const finish = function (fn, arg) {
        if (done) return;
        done = true;
        window.removeEventListener('message', onMsg);
        clearInterval(watch);
        clearTimeout(cap);
        fn(arg);
      };
      const onMsg = function (ev) {
        if (ev.origin !== location.origin) return;
        const d = ev.data;
        if (!d || d.sb !== 'imagine-oauth') return;
        if (d.error) {
          finish(reject, new Error(d.errorDescription || d.error));
          return;
        }
        if (d.state !== state) {
          finish(reject, new Error('The sign-in came back with the wrong state — it was not the window we opened.'));
          return;
        }
        finish(resolve, d.code);
      };
      window.addEventListener('message', onMsg);
      const watch = setInterval(function () {
        if (win.closed) finish(reject, new Error('Sign-in was cancelled.'));
      }, 500);
      const cap = setTimeout(function () {
        try { win.close(); } catch (e) { }
        finish(reject, new Error('Sign-in timed out.'));
      }, 5 * 60 * 1000);
    });
  }

  /* ---------------- who, and how many credits ---------------- */

  let acct = null;   // { email, credits, at }

  function account() { return acct; }

  function whoAmI() {
    return Promise.all([discover(), accessToken()]).then(function (both) {
      const meta = both[0], tok = both[1];
      const ep = meta.userinfo_endpoint || AS_FALLBACK.userinfo_endpoint;
      return fetch(ep, { headers: { Authorization: 'Bearer ' + tok, Accept: 'application/json' } })
        .then(function (res) {
          return jsonOrText(res).then(function (p) {
            if (!res.ok || !p.body) throw apiError(res, p);
            const email = p.body.email || p.body.sub || '';
            const t = tokens();
            if (t) { t.email = email; lsSet(K_TOK, t); }
            acct = { email: email, credits: acct && acct.credits, at: Date.now() };
            notify();
            return acct;
          });
        });
    });
  }

  /* Credits are a tool call, not an endpoint — ImagineArt exposes "balance
   * inquiry" through MCP. Best effort: a number if it can be found, nothing if
   * it cannot. Never blocks a generation. */
  function balance() {
    return callTool('balance', {}).then(function (out) {
      const n = firstNumber(out.text || '') ;
      acct = acct || { email: (tokens() || {}).email || '' };
      if (n !== null) acct.credits = n;
      acct.at = Date.now();
      notify();
      return acct;
    }).catch(function () { return acct; });
  }

  function firstNumber(s) {
    const m = /(-?\d[\d,]*(?:\.\d+)?)/.exec(String(s).replace(/\s+/g, ' '));
    if (!m) return null;
    const n = parseFloat(m[1].replace(/,/g, ''));
    return isFinite(n) ? n : null;
  }

  /* ---------------- MCP transport ----------------
   *
   * Streamable HTTP: one POST per JSON-RPC message, and the answer comes back
   * either as a JSON body or as an SSE stream carrying the same object. Both
   * are handled here so nothing above this cares.
   */
  const mcp = { session: null, ready: null, tools: null, id: 0 };

  /* ---- the headers a browser is actually allowed to send ----
   *
   * mcp.imagine.art answers a preflight with a FIXED allow-list, and neither
   * MCP-Protocol-Version nor Mcp-Session-Id is on it. A browser will not send
   * a non-safelisted header that the server has not allowed, so the preflight
   * fails and fetch rejects before the request exists — the handshake failing
   * with nothing in any log, because nothing was ever sent. curl has no such
   * rule, which is why probing from a terminal said the endpoint was fine.
   *
   * So the protocol version travels where it also belongs, in the initialize
   * params, and the session id is not sent at all — it could not be read back
   * either, since mcp-session-id is not in the server's expose-headers. That
   * makes this a stateless client, which the transport allows.
   *
   * Accept is CORS-safelisted, Content-Type and Authorization are both on the
   * server's list, so what is left preflights cleanly. */
  function mcpPost(msg) {
    return accessToken().then(function (tok) {
      const headers = {
        'Content-Type': 'application/json',
        Accept: 'application/json, text/event-stream',
        Authorization: 'Bearer ' + tok
      };
      return fetch(RESOURCE, { method: 'POST', headers: headers, body: JSON.stringify(msg) })
        .catch(function (e) {
          /* A rejected fetch means it never left the browser. Against this
           * host that is nearly always CORS, and a bare "Failed to fetch" is
           * the least helpful sentence available. */
          const err = new Error('The request never left the browser — ' +
            'ImagineArt\u2019s server did not allow it from this page (CORS). ' +
            (e && e.message ? '[' + e.message + ']' : ''));
          err.cors = true;
          throw err;
        })
        .then(function (res) {
          const sid = res.headers.get('mcp-session-id');
          if (sid) mcp.session = sid;
          if (res.status === 202) return null;          // notification accepted
          return res.text().then(function (text) {
            const obj = parseRpc(text, msg.id);
            if (!res.ok) {
              if (res.status === 401 || res.status === 403) {
                /* The session died under us; a retry after a refresh is the
                 * caller's business, not this layer's. */
                const e = new Error('ImagineArt refused the token.');
                e.auth = true; e.status = res.status;
                throw e;
              }
              throw apiError(res, { body: obj && obj.error, text: text });
            }
            if (obj && obj.error) {
              const e = new Error(obj.error.message || 'ImagineArt returned an error.');
              e.code = obj.error.code;
              throw e;
            }
            return obj ? obj.result : null;
          });
        });
    });
  }

  /* A JSON body, or an SSE stream of them — take the frame that answers our id
   * (or the last one that carries a result, for a server that streams). */
  function parseRpc(text, id) {
    const t = String(text || '').trim();
    if (!t) return null;
    if (t.charAt(0) === '{' || t.charAt(0) === '[') {
      try {
        const j = JSON.parse(t);
        return Array.isArray(j) ? (j.filter(function (x) { return x.id === id; })[0] || j[0]) : j;
      } catch (e) { return null; }
    }
    /* A stream may carry messages that are not ours — the protocol allows it
       — so the frame answering our id wins outright, and anything else is
       only a fallback for a server that does not echo the id. */
    let mine = null, other = null;
    t.split(/\r?\n/).forEach(function (line) {
      const m = /^data:\s*(.*)$/.exec(line);
      if (!m || !m[1] || m[1] === '[DONE]') return;
      let j = null;
      try { j = JSON.parse(m[1]); } catch (e) { return; }
      if (!j) return;
      if (j.id === id) mine = j;
      else if (j.id === undefined && (j.result || j.error)) other = j;
    });
    return mine || other;
  }

  function mcpReady() {
    if (mcp.ready) return mcp.ready;
    mcp.ready = mcpPost({
      jsonrpc: '2.0', id: ++mcp.id, method: 'initialize',
      params: {
        /* the only place the version can travel: the header a browser would
           normally carry it in is not one this server allows */
        protocolVersion: MCP_PROTOCOL,
        capabilities: {},
        clientInfo: { name: CLIENT_NAME, version: String(window.SB_BUILD || 'dev') }
      }
    }).then(function (r) {
      /* The notification is fire-and-forget; a server that does not want it
       * answers 202 or 404 and neither is worth failing over. */
      return mcpPost({ jsonrpc: '2.0', method: 'notifications/initialized', params: {} })
        .catch(function () { return null; })
        .then(function () { return r; });
    }).catch(function (e) {
      mcp.ready = null;
      throw e;
    });
    return mcp.ready;
  }

  function toolList(force) {
    if (mcp.tools && !force) return Promise.resolve(mcp.tools);
    return mcpReady().then(function () {
      return mcpPost({ jsonrpc: '2.0', id: ++mcp.id, method: 'tools/list', params: {} });
    }).then(function (r) {
      mcp.tools = (r && r.tools) || [];
      notify();
      return mcp.tools;
    });
  }

  /* ---------------- the tools ImagineArt actually publishes ----------------
   *
   * Read off a real account's tools/list rather than guessed at. The shape is
   * not what a generic binder would have produced, and three things about it
   * decide how everything below works:
   *
   *   org_id is required on every generation. ImagineArt users can belong to
   *   several organizations and a generation is attributed to one, so nothing
   *   can be made until one is chosen. select_organization lists them; the
   *   server is stateless, so the id rides on every later call.
   *
   *   generation is asynchronous. Both generators return a uuid immediately
   *   and fetch_status reports on it — with sync:true it waits server-side
   *   for about 45 seconds, which turns a poll loop into a few long calls.
   *
   *   a reference image is a URL, never bytes. generate_image takes one
   *   image_url; generate_video takes an ARRAY, where one entry means
   *   animate-this-still and two or more mean reference-to-video. Our frames
   *   are local, so they have to be uploaded first — user_upload takes a file
   *   and an org_id and hands back a URL.
   *
   * The model lists are in the tool descriptions rather than in an enum, so
   * they are parsed from there: "model (optional) — one of: "a", "b", …".
   */
  const TOOL = {
    image: 'generate_image',
    video: 'generate_video',
    status: 'fetch_status',
    upload: 'user_upload',
    orgs: 'select_organization',
    balance: 'get_balance'
  };

  function toolNamed(name) {
    return (mcp.tools || []).filter(function (t) { return t.name === name; })[0] || null;
  }

  /* The models a tool says it takes, in the order it lists them — the first
   * is the one ImagineArt defaults to. */
  function modelsFromTool(name) {
    const t = toolNamed(name);
    const d = (t && t.description) || '';
    const m = /model \(optional\)[^:]*:([\s\S]*?)\. Pass the/.exec(d);
    if (!m) return [];
    const out = [];
    const re = /"([^"]+)"/g;
    let hit;
    while ((hit = re.exec(m[1]))) if (out.indexOf(hit[1]) < 0) out.push(hit[1]);
    return out;
  }

  /* Which aspect ratios and durations a given model will accept, off the same
   * description — so a board asking for 21:9 on a model that only does 16:9
   * can be told rather than silently downgraded. */
  function allowFor(name, model, what) {
    const t = toolNamed(name);
    const d = (t && t.description) || '';
    const sect = new RegExp(what + ' \\(optional\\)[\\s\\S]*?Per-model allow-lists:([\\s\\S]*?)(?:\n\\s*\u2022|$)')
      .exec(d);
    if (!sect) return null;
    const line = new RegExp('-\\s*' + model.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
      ':\\s*([^\n]+)').exec(sect[1]);
    if (!line) return null;
    if (/\(none/.test(line[1])) return [];
    return line[1].split(',').map(function (x) { return x.trim(); })
      .filter(function (x) { return x && !/^\(/.test(x); });
  }

  /* ---- the organisation ---- */

  function org() {
    const all = lsGet(K_ORG) || {};
    return all[catKey()] || null;
  }

  /* The tools want the id, not the record the picker stored. */
  function orgId() {
    const o = org();
    return (o && o.id) || '';
  }

  function setOrg(o) {
    const all = lsGet(K_ORG) || {};
    if (o) all[catKey()] = o; else delete all[catKey()];
    lsSet(K_ORG, all);
    notify();
  }

  /* select_organization renders a picker in a widget client and, in one like
   * this, hands back the list as text. Ids are uuids; names sit beside them. */
  function listOrgs() {
    return callRaw(TOOL.orgs, {}).then(function (got) {
      const text = got.text || JSON.stringify(got.raw || {});
      const out = [];
      const seen = {};
      const re = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/gi;
      let m;
      while ((m = re.exec(text))) {
        const id = m[1];
        if (seen[id]) continue;
        seen[id] = 1;
        /* whatever reads like a name on the same line */
        const line = (text.slice(0, m.index).split('\n').pop() + text.slice(m.index).split('\n')[0]);
        const name = (line.replace(id, '').match(/[A-Za-z][\w .&'-]{1,40}/) || [''])[0].trim();
        out.push({ id: id, name: name || id.slice(0, 8) });
      }
      return out;
    });
  }

  /* ---- picking the tool for a job ----
   *
   * Scored rather than matched, because the names are ImagineArt's to change.
   * "text to image" and "generate_image" both have to win for image, and
   * neither must win for video.
   */
  const WANT = {
    image: { need: [/image|picture|photo/], plus: [/generat|create|text.?to.?image|txt2img/], minus: [/video|upscale|background|remove|music|audio|edit|lipsync|vector/] },
    video: { need: [/video|clip|animat/], plus: [/generat|create|text.?to.?video|image.?to.?video|i2v/], minus: [/upscale|extend|trim|lipsync|music|audio|frame|reframe/] },
    balance: { need: [/balance|credit/], plus: [/inquir|check|remaining/], minus: [] }
  };

  function score(tool, want) {
    const hay = ((tool.name || '') + ' ' + (tool.description || '')).toLowerCase();
    let s = 0;
    if (!want.need.some(function (re) { return re.test(hay); })) return -1;
    want.plus.forEach(function (re) { if (re.test(hay)) s += 2; });
    want.minus.forEach(function (re) { if (re.test(hay)) s -= 3; });
    /* A tool that takes an input image is the right one for image-to-video and
     * the wrong one for a plain still — decided by the caller, not here, so it
     * only breaks ties. */
    s += Math.max(0, 3 - (tool.name || '').length / 20);
    return s;
  }

  function pickTool(kind, opts) {
    return toolList().then(function (tools) {
      const want = WANT[kind];
      let best = null, bestScore = -1;
      tools.forEach(function (t) {
        let s = score(t, want);
        if (s < 0) return;
        if (opts && opts.needsImage) s += hasImageParam(t) ? 4 : -2;
        if (opts && opts.noImage && hasImageParam(t)) s -= 1;
        if (s > bestScore) { bestScore = s; best = t; }
      });
      if (!best) {
        throw new Error('The ImagineArt account exposes no ' + kind +
          ' tool — check Settings → ImagineArt for what it does offer.');
      }
      return best;
    });
  }

  function props(tool) {
    return (tool && tool.inputSchema && tool.inputSchema.properties) || {};
  }

  const IMAGE_PARAM = /^(image|image_url|image_uri|img|file|input_image|start_frame|first_frame|reference_image|init_image|source_image)$/i;

  function hasImageParam(tool) {
    return Object.keys(props(tool)).some(function (k) { return IMAGE_PARAM.test(k); });
  }

  /* ---- filling the arguments ----
   *
   * Canonical fields in, the tool's own property names out. Anything the
   * schema does not ask for is dropped rather than guessed at, and a required
   * enum with no value takes its first option so a call is not refused for
   * want of a field we have no opinion about.
   */
  const SYNONYM = {
    prompt: /^(prompt|text|description|input|query)$/i,
    slug: /^(model|style|model_name|model_id|engine|slug|variant)$/i,
    aspect: /^(aspect_ratio|aspectratio|ratio|aspect)$/i,
    duration: /^(duration|length|seconds|duration_seconds)$/i,
    image: IMAGE_PARAM,
    negative: /^(negative_prompt|negative)$/i
  };

  function bind(tool, canon) {
    const p = props(tool);
    const out = {};
    const used = {};
    Object.keys(canon).forEach(function (field) {
      const v = canon[field];
      if (v === undefined || v === null || v === '') return;
      const re = SYNONYM[field];
      if (!re) return;
      const hit = Object.keys(p).filter(function (k) { return re.test(k) && !used[k]; })[0];
      if (!hit) return;
      used[hit] = 1;
      const spec = p[hit] || {};
      /* An empty enum is not a list of allowed values, it is a schema saying
         nothing — treating it as one refused every model with a message that
         named no alternatives. */
      if (spec.enum && spec.enum.length && spec.enum.indexOf(v) < 0) {
        /* The account's own list is the truth. Something it does not offer is
         * the user's to fix, so say so rather than silently sending something
         * else — an aspect ratio quietly swapped for the first on the list is
         * a square frame where a widescreen one was asked for. */
        const offered = spec.enum.slice(0, 6).join(', ') + (spec.enum.length > 6 ? ', …' : '');
        if (field === 'slug') {
          throw new Error('“' + v + '” is not one of the models this account offers (' +
            offered + ').');
        }
        if (field === 'aspect') {
          throw new Error('This model does not offer ' + v + ' — it takes ' + offered +
            '. Change the aspect ratio in Settings → ImagineArt.');
        }
        return;
      }
      if (spec.type === 'number' || spec.type === 'integer') {
        const n = Number(v);
        /* Sending null for a duration is worse than not sending one. */
        if (!isFinite(n)) return;
        out[hit] = n;
      } else {
        out[hit] = v;
      }
    });
    ((tool.inputSchema && tool.inputSchema.required) || []).forEach(function (k) {
      if (out[k] !== undefined) return;
      const spec = p[k] || {};
      if (spec.default !== undefined) { out[k] = spec.default; return; }
      if (spec.enum && spec.enum.length) { out[k] = spec.enum[0]; return; }
    });
    return out;
  }

  /* A tool call by name with the arguments as published. The scored picker
   * below stays for anything unnamed, but every path this app uses now knows
   * exactly what it is calling. */
  function callRaw(name, args) {
    return mcpReady().then(function () {
      return mcpPost({
        jsonrpc: '2.0', id: ++mcp.id, method: 'tools/call',
        params: { name: name, arguments: args || {} }
      });
    }).then(function (r) {
      if (r && r.isError) throw new Error(harvest(r).text || 'ImagineArt refused the request.');
      return harvest(r);
    });
  }

  /* A generation comes back as a uuid and finishes later. sync:true waits
   * server-side for about 45 seconds, so this is a handful of long calls
   * rather than a busy loop — and it still gives up rather than hanging. */
  function waitForAsset(id, onState) {
    const started = Date.now();
    const look = function () {
      return callRaw(TOOL.status, { id: id, sync: true, org_id: orgId() }).then(function (got) {
        const blob = JSON.stringify((got.raw && got.raw.structuredContent) || {}) + ' ' + (got.text || '');
        const done = /"?status"?\s*[:=]\s*"?(complete|completed|success|finished)/i.test(blob);
        const failed = /"?status"?\s*[:=]\s*"?(error|failed)/i.test(blob);
        if (failed) throw new Error(got.text ? got.text.slice(0, 200) : 'ImagineArt could not finish it.');
        if (got.url && done) return got;
        if (got.url && !/queued|generating|processing|pending/i.test(blob)) return got;
        if (Date.now() - started > 10 * 60 * 1000) {
          throw new Error('Gave up waiting after ten minutes. It may still finish on imagine.art.');
        }
        if (onState) onState('waiting', Date.now() - started);
        return wait(3000).then(look);
      });
    };
    return look();
  }

  /* A local picture has to become a URL before either generator will look at
   * it: the tools take image_url, never bytes. */
  function uploadForUrl(blob) {
    if (!blob) return Promise.resolve('');
    return blobToDataUrl(blob).then(function (data) {
      return callRaw(TOOL.upload, { file: data, org_id: orgId() });
    }).then(function (got) {
      if (!got.url) throw new Error('The upload came back without a URL.');
      return got.url;
    });
  }

  /* Both generators answer with a uuid and finish later. It arrives in the
   * structured content where there is any, and in the prose where there is
   * not. */
  function assetId(got) {
    const sc = (got && got.raw && got.raw.structuredContent) || null;
    const fromSc = sc && (sc.uuid || sc.id || (sc.data && (sc.data.uuid || sc.data.id)));
    if (fromSc && typeof fromSc === 'string') return fromSc;
    const m = /\b([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\b/i
      .exec((got && got.text) || '');
    return m ? m[1] : '';
  }

  function needOrg() {
    if (org()) return '';
    return 'No ImagineArt organization chosen — every generation is billed to one. ' +
      'Settings → ImagineArt picks it.';
  }

  function callTool(kind, canon, opts) {
    return pickTool(kind, opts).then(function (tool) {
      const args = bind(tool, canon);
      return mcpPost({
        jsonrpc: '2.0', id: ++mcp.id, method: 'tools/call',
        params: { name: tool.name, arguments: args }
      }).then(function (r) {
        if (r && r.isError) {
          throw new Error(harvest(r).text || 'ImagineArt refused the request.');
        }
        const got = harvest(r);
        got.tool = tool.name;
        return got;
      });
    });
  }

  /* What came back: inline bytes, a URL, or text that mentions one. */
  function harvest(result) {
    const out = { dataUrl: '', url: '', text: '', raw: result };
    if (!result) return out;
    const content = result.content || [];
    content.forEach(function (c) {
      if (!c) return;
      if ((c.type === 'image' || c.type === 'audio' || c.type === 'video') && c.data) {
        if (!out.dataUrl) out.dataUrl = 'data:' + (c.mimeType || 'image/png') + ';base64,' + c.data;
      } else if (c.type === 'resource' && c.resource) {
        if (c.resource.blob && !out.dataUrl) {
          out.dataUrl = 'data:' + (c.resource.mimeType || 'application/octet-stream') +
            ';base64,' + c.resource.blob;
        }
        if (c.resource.uri && !out.url && /^https?:/.test(c.resource.uri)) out.url = c.resource.uri;
      } else if (c.type === 'resource_link' && c.uri) {
        if (!out.url && /^https?:/.test(c.uri)) out.url = c.uri;
      } else if (c.type === 'text' && c.text) {
        out.text += (out.text ? '\n' : '') + c.text;
      }
    });
    const sc = result.structuredContent;
    if (sc) {
      out.text = out.text || JSON.stringify(sc);
      deepUrl(sc, out);
    }
    if (!out.url && out.text) {
      const m = /(https?:\/\/[^\s")'<>]+)/.exec(out.text);
      if (m) out.url = m[1];
    }
    return out;
  }

  /* A structured reply can carry several URLs — the asset, and a docs or help
   * link beside it. Key order decided which one won, so an error payload
   * mentioning the documentation could be downloaded and filed as the clip.
   * The keys that mean "this is the thing" are preferred, and anything that
   * reads like documentation is taken last. */
  const ASSET_KEY = /^(url|uri|generation|output|result|video|image|asset|file|download|src|link)$/i;
  const DOCSY = /docs?\.|\/docs?\/|help|support|pricing|status\./i;

  function deepUrl(o, out, depth, key) {
    if (!o || (depth | 0) > 5) return;
    if (typeof o === 'string') {
      if (!/^https?:\/\//.test(o)) return;
      const rank = (ASSET_KEY.test(key || '') ? 2 : 0) + (DOCSY.test(o) ? -2 : 0);
      if (!out.url || rank > (out.urlRank | 0)) { out.url = o; out.urlRank = rank; }
      return;
    }
    if (typeof o !== 'object') return;
    Object.keys(o).forEach(function (k) { deepUrl(o[k], out, (depth | 0) + 1, k); });
  }

  /* An expiring CDN link does not fail — it answers 200 with an HTML page
   * saying so. Filing that as an mp4 loses the clip AND removes the warning
   * that would have told anyone to act, so what comes back is checked against
   * what was asked for. */
  function expectMedia(blob, kind) {
    const t = String((blob && blob.type) || '').toLowerCase();
    const ok = kind === 'video'
      ? /^video\//.test(t)
      : /^image\//.test(t);
    if (ok) return blob;
    if (!blob || !blob.size) throw new Error('ImagineArt sent an empty file.');
    /* No type at all is common and usually fine for a direct asset URL; an
     * actively wrong one (a web page, a JSON error) never is. */
    if (!t && blob.size > 1024) return blob;
    const e = new Error('That link did not give back ' +
      (kind === 'video' ? 'a clip' : 'a picture') +
      (t ? ' — it answered with ' + t : ' — it answered with nothing recognisable') +
      '. ImagineArt links expire; shoot it again.');
    e.wrongMedia = true;
    throw e;
  }

  /* ---------------- REST transport ---------------- */

  function apiKey() { return lsStr(K_KEY); }
  function setApiKey(v) { lsPut(K_KEY, (v || '').trim()); notify(); }

  function transport() {
    const m = lsStr(K_MODE);
    return m === 'key' ? 'key' : 'oauth';
  }
  function setTransport(id) { lsPut(K_MODE, id === 'key' ? 'key' : 'oauth'); notify(); }

  /* The bearer to use against api.vyro.ai, or nothing if that door is shut for
   * this session. The OAuth token is offered ONCE; whether it is accepted is
   * remembered so a refused token is not tried again on every press. */
  function restBearer() {
    if (transport() === 'key') {
      const k = apiKey();
      return k ? Promise.resolve(k) : Promise.reject(new Error('No ImagineArt API key — add one in Settings → ImagineArt.'));
    }
    if (lsStr(K_REST) === 'no') return Promise.resolve(null);
    return accessToken().then(function (t) { return t; });
  }

  function restFetch(path, init) {
    return restBearer().then(function (bearer) {
      if (!bearer) return null;
      const o = init || {};
      o.headers = o.headers || {};
      o.headers.Authorization = 'Bearer ' + bearer;
      return fetch(REST + path, o).then(function (res) {
        /* A signed-in session learns here, once, whether its token is good for
         * the REST API at all. */
        if (transport() === 'oauth') {
          if (res.status === 401 || res.status === 403) {
            lsPut(K_REST, 'no');
            return null;
          }
          if (lsStr(K_REST) !== 'yes') lsPut(K_REST, 'yes');
        }
        return res;
      });
    });
  }

  function restImage(canon) {
    const fd = new FormData();
    fd.append('prompt', canon.prompt);
    fd.append('style', canon.slug);
    if (canon.aspect) fd.append('aspect_ratio', canon.aspect);
    return restFetch('/image/generations', { method: 'POST', body: fd }).then(function (res) {
      if (!res) return null;
      const ct = res.headers.get('content-type') || '';
      if (res.ok && ct.indexOf('application/json') < 0) {
        return res.blob().then(function (b) { return { blob: b }; });
      }
      return jsonOrText(res).then(function (p) {
        /* Some models answer asynchronously even here. */
        if (res.ok && p.body && p.body.id) return pollAsset(p.body.id, canon.onState);
        throw apiError(res, p);
      });
    });
  }

  function restVideo(canon) {
    const fd = new FormData();
    fd.append('prompt', canon.prompt);
    fd.append('style', canon.slug);
    if (canon.aspect) fd.append('aspect_ratio', canon.aspect);
    const path = canon.frame ? '/video/image-to-video' : '/video/text-to-video';
    if (canon.frame) fd.append('file', canon.frame, canon.frameName || 'frame.png');
    return restFetch(path, { method: 'POST', body: fd }).then(function (res) {
      if (!res) return null;
      return jsonOrText(res).then(function (p) {
        if (!res.ok || !p.body || !p.body.id) throw apiError(res, p);
        return pollAsset(p.body.id, canon.onState);
      });
    });
  }

  /* Video is minutes, not seconds. Back off from 2s to 10s, give up at ten
   * minutes, and report each look so a row can show that it is still alive. */
  function pollAsset(id, onState) {
    const started = Date.now();
    let gap = 2000;
    const look = function () {
      return restFetch('/assets/' + encodeURIComponent(id) + '/status', { method: 'GET' })
        .then(function (res) {
          if (!res) throw new Error('ImagineArt stopped accepting the session mid-job.');
          return jsonOrText(res).then(function (p) {
            if (!res.ok) throw apiError(res, p);
            const body = p.body || {};
            const asset = body.video || body.image || body.asset || body;
            const st = String(asset.status || body.status || '').toLowerCase();
            const url = (asset.url && (asset.url.generation || asset.url.output)) ||
              asset.url || '';
            if (url && (st === 'finished' || st === 'success' || st === 'completed')) {
              return {
                url: typeof url === 'string' ? url : '',
                thumb: (asset.url && asset.url.thumbnail) || ''
              };
            }
            if (st === 'failed' || st === 'error') {
              throw new Error(asset.message || body.message || 'ImagineArt could not finish that one.');
            }
            if (Date.now() - started > 10 * 60 * 1000) {
              throw new Error('Gave up waiting after ten minutes. The job may still finish on imagine.art.');
            }
            if (onState) onState('waiting', Date.now() - started);
            return wait(gap).then(function () {
              gap = Math.min(10000, Math.round(gap * 1.4));
              return look();
            });
          });
        });
    };
    return look();
  }

  /* ---------------- the two things the app asks for ---------------- */

  function aspectOf(p) {
    return (p && p.settings && p.settings.imagineAspect) || '16:9';
  }

  function slugOf(model) {
    return (model && (model.imagineSlug || '').trim()) || '';
  }

  /* Why a push cannot happen yet, or '' if it can. Said in one place so the
   * button's tooltip and the Settings panel never disagree. */
  function blocker(model) {
    if (transport() === 'key') {
      if (!apiKey()) return 'No ImagineArt API key — Settings → ImagineArt.';
    } else if (!isSignedIn()) {
      return 'Not signed in to ImagineArt — Settings → ImagineArt.';
    } else if (!org()) {
      /* Caught here rather than at the press: every generation is billed to
       * an organization, so without one the button cannot work and should
       * not look as though it can. */
      return 'No ImagineArt organization chosen — Settings → ImagineArt.';
    }
    if (!slugOf(model)) {
      return 'This model has no ImagineArt model set — Settings → Models & templates.';
    }
    return '';
  }

  /* ---------------- which door ----------------
   *
   * Signing in is a choice of surface, not just of billing: the MCP server is
   * ImagineArt's current product and the v2 REST API is an older, smaller one
   * — six image models against the twenty-two the website offers, and a
   * newest Kling of 1.6 against 2.6. A signed-in session that quietly went
   * through REST because the token happened to be accepted there was
   * answering a question the user thought they had already answered.
   *
   * So: signed in means MCP first. REST is the fallback, for the one thing it
   * is definitely better at — it takes an uploaded frame — and for whatever
   * the account's tools turn out not to do. The API-key transport has only
   * ever had REST.
   *
   * Which door actually carried the last generation is recorded, because with
   * a fallback in play "where did this come from" stops being obvious.
   */
  function door() { return lsStr(K_DOOR); }
  function noteDoor(d) { lsPut(K_DOOR, d); }

  function firstOf(primary, fallback) {
    return primary().then(function (r) {
      if (r) return r;
      return fallback();
    }, function (e) {
      /* A token the server rejected is not a reason to try the other door
       * with the same token. */
      if (e && e.auth) throw e;
      return fallback().catch(function () { throw e; });
    });
  }

  /* One still. Resolves to {blob, dataUrl}. */
  function image(opts) {
    const canon = {
      prompt: opts.prompt, slug: opts.slug,
      aspect: opts.aspect, onState: opts.onState
    };
    const viaMcp = function () {
      const why = needOrg();
      if (why) return Promise.reject(new Error(why));
      /* aspect_ratio, model and duration are required-but-nullable on this
       * tool, so the keys travel even when there is nothing to put in them. */
      const args = {
        org_id: orgId(),
        prompt: canon.prompt,
        model: canon.slug || null,
        aspect_ratio: canon.aspect || null,
        duration: null,
        image_url: opts.imageUrl || null
      };
      return callRaw(TOOL.image, args).then(function (got) {
        const id = assetId(got);
        return (got.url && !id) ? got : waitForAsset(id || got.text, canon.onState);
      }).then(function (got) {
        noteDoor('mcp');
        return finishImage(got);
      });
    };
    const viaRest = function () {
      return restImage(canon).then(function (got) {
        if (!got) return null;
        noteDoor('rest');
        return finishImage(got);
      });
    };
    if (transport() === 'key') {
      return viaRest().then(function (r) {
        if (!r) throw new Error('ImagineArt did not answer with a picture.');
        return r;
      });
    }
    return firstOf(viaMcp, function () {
      return viaRest().then(function (r) {
        if (!r) throw new Error('Neither your account\u2019s tools nor the REST API made that ' +
          'picture. Settings → ImagineArt → what my account can do says what it offers.');
        return r;
      });
    });
  }

  function finishImage(got) {
    if (got.blob) {
      return blobToDataUrl(got.blob).then(function (d) { return { blob: got.blob, dataUrl: d }; });
    }
    if (got.dataUrl) {
      return dataUrlToBlob(got.dataUrl).then(function (b) {
        return { blob: b, dataUrl: got.dataUrl };
      });
    }
    if (got.url) {
      /* The CDN may or may not allow a cross-origin read. If it does we get the
       * original bytes; if it does not, the URL is still worth handing back. */
      return fetch(got.url).then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.blob();
      }).then(function (b) {
        return expectMedia(b, 'image');
      }).then(function (b) {
        return blobToDataUrl(b).then(function (d) { return { blob: b, dataUrl: d, url: got.url }; });
      }).catch(function () {
        return { blob: null, dataUrl: '', url: got.url };
      });
    }
    throw new Error('ImagineArt answered without a picture' + (got.text ? ': ' + got.text.slice(0, 160) : '.'));
  }

  /* One clip. `frame` is a Blob to animate from, or nothing for text-to-video.
   * Resolves to {blob, url, thumb} — blob may be null if the CDN refuses a
   * cross-origin read, and the URL is then all there is. */
  function video(opts) {
    const canon = {
      prompt: opts.prompt, slug: opts.slug, aspect: opts.aspect,
      duration: opts.duration, frame: opts.frame, frameName: opts.frameName,
      onState: opts.onState
    };
    const viaMcp = function () {
      const why = needOrg();
      if (why) return Promise.reject(new Error(why));
      /* One image means "animate this still"; two or more would mean
       * reference-to-video, which only some models take. The frame is local,
       * so it has to become a URL first. */
      return (opts.frame ? uploadForUrl(opts.frame) : Promise.resolve(''))
        .then(function (url) {
          const args = {
            org_id: orgId(),
            prompt: canon.prompt,
            model: canon.slug || null,
            aspect_ratio: canon.aspect || null,
            duration: canon.duration ? String(canon.duration) : null,
            image_url: url ? [url] : null
          };
          return callRaw(TOOL.video, args);
        })
        .then(function (got) {
          const id = assetId(got);
          return (got.url && !id) ? got : waitForAsset(id || got.text, canon.onState);
        })
        .then(function (got) { noteDoor('mcp'); return finishVideo(got); });
    };
    const viaRest = function () {
      return restVideo(canon).then(function (got) {
        if (!got) return null;
        noteDoor('rest');
        return finishVideo(got);
      });
    };
    if (transport() === 'key') {
      return viaRest().then(function (r) {
        if (!r) throw new Error('ImagineArt did not answer with a clip.');
        return r;
      });
    }
    return firstOf(viaMcp, function () {
      return viaRest().then(function (r) {
        if (!r) throw new Error('Neither your account\u2019s tools nor the REST API made that ' +
          'clip. Settings → ImagineArt → what my account can do says what it offers.');
        return r;
      });
    });
  }

  function finishVideo(got) {
    const url = got.url || '';
    if (got.blob) return Promise.resolve({ blob: got.blob, url: url, thumb: got.thumb || '' });
    if (got.dataUrl) {
      return dataUrlToBlob(got.dataUrl).then(function (b) {
        return { blob: b, url: url, thumb: got.thumb || '' };
      });
    }
    if (!url) {
      throw new Error('ImagineArt answered without a clip' + (got.text ? ': ' + got.text.slice(0, 160) : '.'));
    }
    return fetch(url).then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.blob();
    }).then(function (b) {
      return { blob: expectMedia(b, 'video'), url: url, thumb: got.thumb || '' };
    }).catch(function () {
      /* No bytes: the link is all there is, and the board says so rather than
       * filing whatever came back. */
      return { blob: null, url: url, thumb: got.thumb || '' };
    });
  }

  /* ---------------- jobs ----------------
   *
   * A clip takes minutes and the prompt table re-renders on every keystroke,
   * so what is in flight cannot live on a DOM node. It lives here, keyed by
   * shot and role, and the table reads it. Closing the panel mid-job and
   * opening it again finds the job exactly where it was.
   */
  const JOBS = {};
  const LISTENERS = [];

  function key(shotId, role) { return shotId + ':' + role; }

  function job(shotId, role) { return JOBS[key(shotId, role)] || null; }
  function busy(shotId, role) {
    const j = job(shotId, role);
    return !!(j && (j.state === 'working' || j.state === 'waiting'));
  }

  function onChange(fn) {
    LISTENERS.push(fn);
    return function () {
      const i = LISTENERS.indexOf(fn);
      if (i >= 0) LISTENERS.splice(i, 1);
    };
  }

  let pending = null;
  function notify() {
    /* Several fields move at once at the start and end of a job; one repaint
     * covers them. */
    if (pending) return;
    pending = setTimeout(function () {
      pending = null;
      LISTENERS.slice().forEach(function (fn) {
        try { fn(); } catch (e) { }
      });
    }, 0);
  }

  function start(shotId, role) {
    const j = { shotId: shotId, role: role, state: 'working', started: Date.now(), error: '' };
    JOBS[key(shotId, role)] = j;
    notify();
    return j;
  }

  function endJob(shotId, role, error) {
    const k = key(shotId, role);
    const j = JOBS[k];
    if (!j) return;
    if (error) {
      j.state = 'error';
      j.error = error.message || String(error);
      j.ended = Date.now();
      /* An error stays on the row until the next press — it is the only place
       * the reason is written down. */
    } else {
      delete JOBS[k];
    }
    notify();
  }

  /* Clearing is for the error a row is still showing, not for a generation
   * that is in the air: dropping the record would take the guard off and let
   * a second one start — two clips, two charges, one shot. A running job ends
   * when it ends. */
  function clear(shotId, role) {
    if (busy(shotId, role)) return false;
    delete JOBS[key(shotId, role)];
    notify();
    return true;
  }

  /* ---------------- run one ----------------
   *
   * The single entry point the prompt table uses: one press, one generation,
   * results filed where the rest of the app already looks for them.
   */
  function run(shot, role) {
    const p = SB.app.project;
    if (busy(shot.id, role)) return Promise.resolve(null);

    const model = role === 'image' ? SB.Model.imageModel(p) : SB.Model.videoModel(p);
    const why = blocker(model);
    if (why) return Promise.reject(new Error(why));

    /* The button refuses one of these too, but run() is the public door and
     * has to hold the same line on its own. */
    if (shot.noShot) {
      return Promise.reject(new Error('A “no shot” card is never generated.'));
    }

    const pr = shot.prompts && shot.prompts[model.id];
    const text = pr && (role === 'image' ? pr.imagePrompt : pr.videoPrompt);
    if (!(text || '').trim()) {
      return Promise.reject(new Error('There is no ' +
        (role === 'image' ? 'first-frame' : 'video') + ' prompt on this shot yet.'));
    }

    /* An image-to-video model with no frame, or a text-to-video one with a
     * frame in hand, is a wasted generation — and on this platform the two
     * are different slugs, not a flag. Caught before the credits go. */
    /* Only the v2 REST API splits a model into a text-to-video slug and an
     * image-to-video one. The account's tools take one model and decide from
     * whether an image came with it, so this check is about the REST
     * transport and would be nonsense on the other. */
    if (role === 'video' && transport() === 'key') {
      const info = modelInfo(slugOf(model));
      const has = !!(shot.render || shot.image);
      if (info && info.mode === 't2v' && has) {
        return Promise.reject(new Error('“' + slugOf(model) + '” is a text-to-video model, and ' +
          'this shot has a frame to animate. Point this model at the matching ' +
          'image-to-video slug in Settings → Models & templates.'));
      }
      if (info && info.mode === 'i2v' && !has) {
        return Promise.reject(new Error('“' + slugOf(model) + '” animates a picture, and this ' +
          'shot has none yet. Render the first frame, or use the text-to-video slug.'));
      }
    }

    const j = start(shot.id, role);
    const state = function (s) { j.state = s; notify(); };

    /* Stamped onto whatever comes back, because an export that can say "these
     * eleven were generated, off these prompts, by this model" is a different
     * thing from one that hands over a folder of pictures. */
    const made = {
      by: 'imagine', role: role, model: model.name, modelId: model.id, slug: slugOf(model),
      via: transport(), at: Date.now()
    };
    /* Which picture this clip is being made from, so it can be filed against
     * that picture however the board is rearranged in the meantime. */
    const frameRef = (shot.image && shot.image.ref) || '';

    const work = role === 'image'
      ? image({ prompt: text, slug: slugOf(model), aspect: aspectOf(p), onState: function () { state('waiting'); } })
        .then(function (got) { return fileImage(p, shot, got, made); })
      : startFrame(p, shot).then(function (frame) {
        return video({
          prompt: text, slug: slugOf(model), aspect: aspectOf(p),
          frame: frame && frame.blob, frameName: frame && frame.name,
          onState: function () { state('waiting'); }
        });
      }).then(function (got) {
        return fileVideo(p, targetFor(p, shot, frameRef), got, made);
      });

    return work.then(function (out) {
      endJob(shot.id, role);
      /* It produced something, so whatever any list says, this slug is real
       * for this account. */
      noteWorked(slugOf(model), role === 'image' ? 'image' : 'video');
      return out;
    }).catch(function (e) {
      endJob(shot.id, role, e);
      throw e;
    });
  }

  /* The frame a clip animates from: the full-size original the board is
   * carrying, its ≤480p proxy if the original predates them being kept in the
   * file, and nothing at all if the shot has no picture — which is a
   * text-to-video, not a failure. */
  function startFrame(p, shot) {
    return SB.Renders.file(p, shot.render).then(function (f) {
      if (f) return { blob: f, name: f.name };
      const src = shot.image ? SB.Blobs.src(p, shot.image) : '';
      if (!src) return null;
      return dataUrlToBlob(src).then(function (b) { return { blob: b, name: 'frame.jpg' }; });
    }).catch(function () { return null; });
  }

  /* A generated still is filed exactly like a dropped one — proxy on the
   * board, original in the file under its serial. Which is the point: the
   * next shot can reference it ten seconds later, and so can whoever the
   * board is handed to. */
  function fileImage(p, shot, got, made) {
    if (!got.blob) {
      throw new Error('ImagineArt made the picture but this browser could not read it back' +
        (got.url ? ' — it is at ' + got.url : '.'));
    }
    return SB.Board.setImage(shot, got.blob, made).then(function () {
      return { kind: 'image' };
    });
  }

  /* Minutes pass between asking for a clip and filing it, which is plenty of
   * time for two cards to be swapped. A clip belongs to the frame it was
   * animated from, so it is filed against that picture rather than against
   * the card that asked. */
  function targetFor(p, shot, frameRef) {
    if (!frameRef) return shot;
    if (shot.image && shot.image.ref === frameRef) return shot;
    return SB.Model.shotHolding(p, frameRef) || shot;
  }

  function fileVideo(p, shot, got, made) {
    const rec = { at: Date.now(), url: got.url || '', thumb: got.thumb || '', made: made || null };
    if (!got.blob) {
      /* ImagineArt made it but the browser could not read the bytes back
       * across origins: hold the link, say so, and leave a way to try again
       * while the link is still alive. */
      shot.video = rec;
      SB.app.changed(true);
      return Promise.resolve({ kind: 'video', remoteOnly: true });
    }
    return SB.Renders.keepVideo(p, got.blob, shot.video, made).then(function (saved) {
      /* The whole record, ref included. Rebuilding it field by field dropped
       * the ref once, which put the bytes in the file with nothing pointing at
       * them — so the clip played until the next structural change swept it
       * away, and then the board had a link and no clip. */
      if (saved) {
        saved.url = rec.url;
        saved.thumb = rec.thumb;
      }
      shot.video = saved || rec;
      SB.app.changed(true);
      return { kind: 'video', remoteOnly: !saved };
    });
  }

  /* A second chance at a clip whose bytes never arrived. The link ImagineArt
   * hands back works for a while and then does not, so this is worth reaching
   * for the moment the board says "link only" rather than later. */
  function fetchClip(shot) {
    const p = SB.app.project;
    const rec = shot && shot.video;
    if (!rec || rec.ref) return Promise.resolve(false);
    if (!rec.url) return Promise.reject(new Error('That clip has no link left to fetch from.'));
    return fetch(rec.url).then(function (r) {
      if (!r.ok) throw new Error('ImagineArt answered ' + r.status);
      return r.blob();
    }).then(function (b) {
      return SB.Renders.keepVideo(p, expectMedia(b, 'video'), rec, rec.made);
    }).then(function (saved) {
      if (!saved) throw new Error('the clip could not be stored');
      saved.url = rec.url;
      saved.thumb = rec.thumb;
      shot.video = saved;
      SB.app.changed(true);
      return true;
    });
  }

  /* ---------------- what Settings shows ---------------- */

  /* What the account itself advertises. Read per tool, so the kind comes from
   * the tool the enum was on rather than from guessing at the slug's spelling
   * — which is how "wan" ended up classified by a regex of model names I
   * happened to think of. */
  /* What the account's own tools say they take.
   *
   * ImagineArt publishes its model lists in prose inside the tool
   * description rather than as a JSON enum, so they are parsed from there —
   * and the first one listed is the default that tool uses. Nothing here is
   * a guess about spelling: the kind comes from which tool the list was on.
   *
   * An enum is still read where a tool has one, for any server that does it
   * the ordinary way. */
  function fromAccount() {
    const out = [];
    const seen = {};
    const take = function (slug, kind, extra) {
      if (typeof slug !== 'string' || !slug || seen[slug]) return;
      seen[slug] = 1;
      out.push(Object.assign({ slug: slug, kind: kind, from: 'account' }, extra || {}));
    };
    modelsFromTool(TOOL.image).forEach(function (m, i) {
      take(m, 'image', { deflt: i === 0 });
    });
    modelsFromTool(TOOL.video).forEach(function (m, i) {
      take(m, 'video', { deflt: i === 0 });
    });
    (mcp.tools || []).forEach(function (t) {
      if (t.name === TOOL.image || t.name === TOOL.video) return;
      const kind = score(t, WANT.video) > score(t, WANT.image) ? 'video' : 'image';
      const ps = props(t);
      Object.keys(ps).forEach(function (k) {
        if (!SYNONYM.slug.test(k)) return;
        (ps[k].enum || []).forEach(function (v) { take(v, kind); });
      });
    });
    return out;
  }

  function catKey() {
    const t = tokens();
    return (transport() === 'key' ? 'key' : ((t && t.email) || 'signed-in'));
  }

  function cachedCatalog() {
    const all = lsGet(K_CAT) || {};
    return all[catKey()] || null;
  }

  function storeCatalog(list) {
    const all = lsGet(K_CAT) || {};
    all[catKey()] = { at: Date.now(), list: list };
    lsSet(K_CAT, all);
  }

  /* Ask the account what it offers, and say what moved. Called on sign-in, by
   * the Refresh button, when Settings opens on a stale cache, and when a push
   * is refused for a slug the account does not know — that refusal is the
   * catalog telling us it has changed. */
  function refreshCatalog() {
    if (!isSignedIn()) {
      return Promise.reject(new Error('Sign in and this becomes whatever your account offers.'));
    }
    const was = (cachedCatalog() || {}).list || [];
    return toolList(true).then(function () {
      const now = fromAccount();
      if (!now.length) {
        /* Tools with no enum is not an empty catalog. */
        const e = new Error('Your account\u2019s tools do not publish a model list, so the ' +
          'built-in one stands.');
        e.soft = true;
        throw e;
      }
      storeCatalog(now);
      const had = {};
      was.forEach(function (x) { had[x.slug] = 1; });
      const has = {};
      now.forEach(function (x) { has[x.slug] = 1; });
      return {
        list: now, at: Date.now(),
        added: now.filter(function (x) { return was.length && !had[x.slug]; })
          .map(function (x) { return x.slug; }),
        gone: was.filter(function (x) { return !has[x.slug]; }).map(function (x) { return x.slug; })
      };
    });
  }

  function catalogAge() {
    const c = cachedCatalog();
    return c ? Date.now() - c.at : null;
  }

  /* Where the list on screen came from, so nobody mistakes my notes for their
   * account. */
  function catalogSource() {
    const c = cachedCatalog();
    if (c && c.list && c.list.length) return 'account';
    return (SB.ImagineModels && SB.ImagineModels.list && SB.ImagineModels.list.length)
      ? 'shipped' : 'fallback';
  }

  function catalogAll() {
    const c = cachedCatalog();
    const base = (c && c.list && c.list.length) ? c.list : shipped();
    /* Proven slugs first, and never dropped for being absent from a list. */
    const proven = worked();
    if (!proven.length) return base;
    const have = {};
    proven.forEach(function (x) { have[x.slug] = 1; });
    return proven.concat(base.filter(function (m) { return !have[m.slug]; }));
  }

  /* Every model of a kind, most useful first — the account's own, then the
   * shipped list for anything it did not mention. */
  function catalog(kind) {
    return catalogAll()
      .filter(function (m) { return !kind || m.kind === kind; })
      .map(function (m) { return m.slug; });
  }

  /* ---------------- what has actually worked ----------------
   *
   * Every published list is behind the product — the v2 API's by a year, the
   * documentation's by months — and imagine.art is an aggregator, so the set
   * of models it carries moves whenever a third party ships one. FLUX 3 and
   * Veo are on the platform and in neither list.
   *
   * The one source that cannot be stale is a generation that worked. A slug
   * that produced something is recorded against the account and offered from
   * then on, whatever any catalog says — so the app converges on what is
   * true for the person using it rather than on what somebody published. */
  function worked() {
    const all = lsGet(K_WORKED) || {};
    return all[catKey()] || [];
  }

  function noteWorked(slug, kind) {
    const s = String(slug || '').trim();
    if (!s) return;
    const all = lsGet(K_WORKED) || {};
    const mine = all[catKey()] || [];
    const at = mine.filter(function (x) { return x.slug === s; })[0];
    if (at) { at.at = Date.now(); at.n = (at.n | 0) + 1; }
    else mine.push({ slug: s, kind: kind, at: Date.now(), n: 1, from: 'worked' });
    all[catKey()] = mine;
    lsSet(K_WORKED, all);
  }

  function modelInfo(slug) {
    const s = String(slug || '').trim();
    if (!s) return null;
    return catalogAll().filter(function (m) { return m.slug === s; })[0] || null;
  }

  /* ---------------- playing one back ----------------
   *
   * The clip is in the file, so playing it is reading it back out of the blob
   * map — with the remote copy as the fallback for the one case where the
   * bytes never arrived, and where the link is all there is and will not last.
   */
  function playClip(p, shot) {
    const rec = shot && shot.video;
    if (!rec) return;
    SB.Renders.videoFile(p, rec).then(function (f) {
      const src = f ? URL.createObjectURL(f) : (rec.url || '');
      if (!src) {
        SB.toast('This board has no copy of that clip, and its link has gone', true);
        return;
      }
      const box = SB.el('div', 'clip-box');
      const v = document.createElement('video');
      v.src = src;
      v.controls = true;
      v.autoplay = true;
      v.loop = true;
      box.appendChild(v);
      if (!f && rec.url) {
        const note = SB.el('div', 'pp-note warn',
          'Played from ImagineArt — this board has no copy of its own, and that link expires. ');
        const grab = SB.el('button', 'mini', 'bring it into the board');
        grab.onclick = function () {
          grab.disabled = true;
          grab.textContent = 'fetching…';
          SB.Imagine.fetchClip(shot).then(function (ok) {
            SB.toast(ok ? 'Clip is in the board now' : 'Nothing to fetch');
            grab.remove();
          }).catch(function (e) {
            grab.disabled = false;
            grab.textContent = 'bring it into the board';
            SB.toast(e.message, true);
          });
        };
        note.appendChild(grab);
        box.appendChild(note);
      }
      const line = clipLabel(rec);
      if (line) box.appendChild(SB.el('div', 'pp-note', line + (rec.name ? ' · ' + rec.name : '')));

      const acts = SB.el('div', 'pp-actions');
      const swap = SB.el('button', 'tb', 'Replace…');
      swap.title = 'Put a different file on this card';
      swap.onclick = function () {
        SB.pickVideoFile().then(function (file) {
          if (!file) return;
          return attachClip(p, shot, file).then(function () {
            SB.toast('Clip replaced');
            m.close();
          });
        }).catch(function (e) { SB.toast(e.message || String(e), true); });
      };
      const rm = SB.el('button', 'tb danger', 'Remove');
      rm.title = 'Take the clip off this card. The bytes go with it.';
      SB.armButton(rm, 'remove for good', function () {
        dropClip(p, shot);
        SB.toast('Clip removed');
        m.close();
      });
      acts.appendChild(swap);
      acts.appendChild(rm);
      box.appendChild(acts);

      const m = SB.modal({
        title: 'Clip',
        width: '760px',
        body: box,
        buttons: [{ label: 'Close', primary: true }],
        onClose: function () {
          v.pause();
          if (f) URL.revokeObjectURL(src);
        }
      });
    });
  }

  /* How long it runs and how big it is, read off the file itself. Worth the
   * round trip: a badge that says "5s" is the difference between a card that
   * has something and a card whose clip you have to open to identify. Failing
   * to read it is not a failure to keep it. */
  function clipMeta(blob) {
    return new Promise(function (resolve) {
      let url = '';
      let done = false;
      const finish = function (meta) {
        if (done) return;
        done = true;
        if (url) URL.revokeObjectURL(url);
        resolve(meta || {});
      };
      try {
        url = URL.createObjectURL(blob);
        const v = document.createElement('video');
        v.preload = 'metadata';
        v.onloadedmetadata = function () {
          finish({
            dur: isFinite(v.duration) ? Math.round(v.duration * 10) / 10 : 0,
            w: v.videoWidth || 0, h: v.videoHeight || 0
          });
        };
        v.onerror = function () { finish(null); };
        v.src = url;
      } catch (e) { finish(null); }
      setTimeout(function () { finish(null); }, 4000);
    });
  }

  /* A clip made somewhere else — rendered last month, cut in Premiere, handed
   * over by somebody — put on a card. Nothing generated it here, so it carries
   * no `made` and the export's "only what was made in here" filter correctly
   * passes it by. */
  function attachClip(p, shot, file) {
    if (!file) return Promise.resolve(null);
    if (!/^video\//.test(file.type || '')) {
      return Promise.reject(new Error('That is not a video file.'));
    }
    return clipMeta(file).then(function (meta) {
      return SB.Renders.keepVideo(p, file, shot.video).then(function (saved) {
        if (!saved) throw new Error('the clip could not be stored');
        if (meta.dur) saved.dur = meta.dur;
        if (meta.w) { saved.w = meta.w; saved.h = meta.h; }
        saved.name = file.name || '';
        shot.video = saved;
        SB.app.changed(true);
        return saved;
      });
    });
  }

  function dropClip(p, shot) {
    if (!shot || !shot.video) return;
    shot.video = null;
    SB.app.changed(true);
  }

  /* "5s · 1184×672 · 1.9 MB", as much of it as is known. */
  function clipLabel(rec) {
    if (!rec) return '';
    const bits = [];
    if (rec.dur) bits.push(rec.dur + 's');
    if (rec.w) bits.push(rec.w + '×' + rec.h);
    if (rec.bytes) bits.push((rec.bytes / 1048576).toFixed(1) + ' MB');
    if (!rec.ref) bits.push('link only');
    return bits.join(' · ');
  }

  /* ---------------- the connection, step by step ----------------
   *
   * "It didn't work" is the least useful sentence in software, and a toast
   * that says why and then vanishes after two seconds is how you get it. This
   * walks the whole path — signed in, discovery, token, handshake, tools —
   * and reports each step as it goes, so a failure names the step, the
   * status and the message instead of disappearing.
   *
   * Never rejects: a broken connection is the thing being described. */
  function report() {
    const steps = [];
    const add = function (name, ok, detail) { steps.push({ name: name, ok: ok, detail: detail || '' }); };
    const bail = function (name) {
      return function (e) {
        add(name, false, (e && e.message) || String(e));
        const stop = new Error('stopped');
        stop.stopped = true;
        throw stop;
      };
    };

    if (transport() === 'key') {
      add('Transport', true, 'API key — MCP is not used, so there are no tools to list. ' +
        'Switch to “Sign in with ImagineArt” above to see an account’s own tools.');
      add('API key', !!apiKey(), apiKey() ? 'set in this browser' : 'none set');
      return Promise.resolve(steps);
    }

    add('Signed in', isSignedIn(),
      isSignedIn() ? ((tokens() || {}).email || 'yes') : 'no — press Sign in first');
    if (!isSignedIn()) return Promise.resolve(steps);

    return discover().then(function (meta) {
      add('Discovery', !!(meta && meta.token_endpoint), (meta && meta.issuer) || 'no metadata');
      return accessToken();
    }, bail('Discovery')).then(function () {
      const t = tokens() || {};
      const left = Math.round(((t.expires_at || 0) - Date.now()) / 60000);
      add('Access token', true, left > 0 ? 'good for ' + left + ' more minutes' : 'refreshed');
      return mcpReady();
    }, bail('Access token')).then(function (r) {
      const si = r && r.serverInfo;
      add('MCP handshake', true, si ? ((si.name || 'server') + ' ' + (si.version || '')).trim()
        : 'accepted');
      return toolList(true);
    }, function (e) {
      add('MCP handshake', false, ((e && e.message) || String(e)) +
        (e && e.cors ? ' — nothing was sent, so nothing was billed.' : '') +
        (e && e.status ? ' (HTTP ' + e.status + ')' : ''));
      const stop = new Error('stopped');
      stop.stopped = true;
      throw stop;
    }).then(function (list) {
      add('Tools', !!(list && list.length), (list || []).length + ' offered');
      const rest = lsStr(K_REST);
      if (rest) {
        add('v2 REST fallback', rest === 'yes',
          rest === 'yes' ? 'your token is accepted there too' : 'your token is not accepted there');
      }
      const named = [TOOL.image, TOOL.video, TOOL.status].filter(toolNamed);
      add('The tools this app uses', named.length === 3,
        named.length === 3
          ? TOOL.image + ', ' + TOOL.video + ', ' + TOOL.status
          : 'missing: ' + [TOOL.image, TOOL.video, TOOL.status].filter(function (n) {
            return !toolNamed(n);
          }).join(', '));
      const o = org();
      add('Organization', !!o, o ? (o.name || o.id) + ' — every generation is billed to it'
        : 'not chosen yet; nothing can be generated until it is');
      return steps;
    }, function (e) {
      if (!e || !e.stopped) add('Tools', false, (e && e.message) || String(e));
      return steps;
    }).catch(function () { return steps; });
  }

  /* Everything the account's tools say about themselves, flattened for
   * reading. The whole question of which models an OAuth session can reach —
   * and whether it can even be asked for one — is answered by this and
   * nothing else, and it cannot be answered from outside an account at all.
   * So it is one button rather than a support thread. */
  function capabilities() {
    return toolList(true).then(function (tools) {
      return (tools || []).map(function (t) {
        const ps = props(t);
        const req = (t.inputSchema && t.inputSchema.required) || [];
        return {
          name: t.name,
          description: t.description || '',
          takesImage: hasImageParam(t),
          params: Object.keys(ps).map(function (k) {
            const spec = ps[k] || {};
            return {
              name: k,
              type: spec.type || '',
              required: req.indexOf(k) >= 0,
              enum: Array.isArray(spec.enum) ? spec.enum.slice() : null,
              isModel: SYNONYM.slug.test(k)
            };
          })
        };
      });
    });
  }

  SB.Clip = {
    play: playClip, attach: attachClip, drop: dropClip,
    label: clipLabel, meta: clipMeta
  };

  SB.Imagine = {
    /* config */
    transport: transport, setTransport: setTransport,
    apiKey: apiKey, setApiKey: setApiKey,
    signInBlocked: signInBlocked, redirectUri: redirectUri,
    /* auth */
    signIn: signIn, signOut: signOut, isSignedIn: isSignedIn,
    account: account, whoAmI: whoAmI, balance: balance,
    /* discovery, for the Settings readout */
    discover: discover, toolList: toolList, tools: function () { return mcp.tools || []; },
    capabilities: capabilities, report: report, door: door,
    restVerdict: function () { return lsStr(K_REST); },
    catalog: catalog, catalogAll: catalogAll, catalogSource: catalogSource,
    worked: worked, noteWorked: noteWorked,
    org: org, orgId: orgId, setOrg: setOrg, listOrgs: listOrgs, needOrg: needOrg,
    allowFor: allowFor, modelsFromTool: modelsFromTool, TOOL: TOOL,
    _assetId: assetId,
    catalogAge: catalogAge, refreshCatalog: refreshCatalog,
    modelInfo: modelInfo, labelFor: labelFor,
    guessSlug: function (name) { return GUESS[name] || ''; },
    /* work */
    ready: function (model) { return !blocker(model); },
    blocker: blocker, slugOf: slugOf, aspectOf: aspectOf,
    image: image, video: video, run: run, fetchClip: fetchClip,
    /* jobs */
    job: job, busy: busy, clear: clear, onChange: onChange,
    /* exposed for the tests */
    _bind: bind, _pickScore: score, _harvest: harvest, _parseRpc: parseRpc,
    _fileVideo: fileVideo
  };

})(window.SB);
